Feature branch
AbdelrhmanAmin/Advanced-Building-Blocks---Enumerables pull request #1
Opened 2020-11-26 21:39 UTC by AbdelrhmanAmin

2020-11-26 21:49 UTC, AbdelrhmanAmin commented
> _No description provided._

2020-11-27 07:22 UTC, kitpao requested changes
# 👋 Hello @AbdelrhmanAmin 

- [x] The reason Rubocop is complaining is that you have an extra `end` in line 106. Please check all your indentation, it is causing issues in your logic. Remember you have to use 2 spaces of indentation when you use a loop or an if and leave everything in the same level in the same indentation line. Finally, run Rubocop again, you will have different errors, I will leave you an example of good indentation:
![image](https://user-images.githubusercontent.com/53256139/100419292-e8b73a00-3049-11eb-9238-ca89528e5784.png)


- [x] The second error you have right now in Rubocop is in the test.rb file, this file is not required, you can add it to gitignore. But if you want to fix it, you just have to delete the parenthesis -> `puts 1..5.my_map(&my_proc)`

### Methods:
  **Tip:** You can see the complete [description of all the methods here](https://ruby-doc.org/core-2.6.5/Enumerable.html), please check it out as a guide if you feel lost

#### #my_each
- [x] when a block is given when self is a range returns the range itself after calling the given block once for each element in self -> This means you have to return the same input (return at the end self, you are returning the modified input converted into an array, take the case of ranges)

#### #my_each_with_index
- [x] when a block is given when self is an array returns the array itself after calling the given block once for each element in self -> This means you have to return the same input (return at the end self, you are returning the modified input converted into an array, take the case of ranges)

#### #my_all?
  - [x] Please notice the difference between expected and result:
  ```
  p [1,2,3].all?                 # correct answer: false
  p [1,2,3].my_all?(3)      # your method returns true
  ```

#### #my_any?
  - [x] `['e', 'dd'].my_any?(/d/)` should be true because one of the elements matches with /d/ regexp
  - [x] `[1,2,3].my_any?(3)` should be true because one of the elements matches with 3

#### #my_none?
  - [x] `['e', 'dd'].my_none?(/d/)` should be false because one of the elements matches with /d/ regexp
  - [x] `[1,2,3].my_none?(3)` should be false because one of the elements matches with 3

#### #my_count
  - [x] Please notice this method should not have "?" in the name

#### #my_map
  - [x] This method should return an enumerator if no block is given

#### #my_inject
   - [x] Your method should also be able to multiply elements without a block, `[2,3].my_inject(20, :*)` should return 120 (20 * 2 * 3)
  - [x]  `[2,3,4].my_inject(:+)` should return 9 -> 2+3+4=9. Your code gives an error if no block is given

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-27 07:22 UTC, kitpao commented on index.rb
> +end
- [x] be careful with your indentation so that you have less trouble finding errors in your code

2020-11-27 07:22 UTC, kitpao commented on README.md
> +- in terminal type: ruby bubble_sort.rb
- [x] Please update the instructions for this project (instead of bubble_sort.rb)

2020-11-27 07:22 UTC, kitpao commented on Gemfile
> +# gem "rails"
- [x] Please delete commented code
![image](https://user-images.githubusercontent.com/53256139/100417532-c66fed00-3046-11eb-884b-b4fd3db9dbd7.png)

2020-11-27 20:24 UTC, kitpao requested changes
# 👋 Hello @AbdelrhmanAmin 

You progressed quite a lot 👏 Most tests are passing and you managed to fix issues with the linters (you can edit and take out that message from the pull request message if you want)

You still have test cases in 3 methods that are not passing, please check below 🔽 

#### #my_any?
- [ ] Seems like your code is now not working with strings as arguments `["car","cat","dog"].my_any?("cat")` should be true

#### #my_none?
- [ ] Same happens in my_none: `["car","cat","dog"].my_none?("cat")` should be false because there is a cat.
- [ ] `p [1,2,2].my_none?(3)` should be true because there is no 3

#### #my_inject
  - [ ] If there is no block or argument, your method should return a local jump error ([how to raise errors here](https://stackoverflow.com/questions/4325507/how-to-force-a-localjumperror-on-return-in-ruby))

That is all 😄 you are almost there 🏅 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-27 20:24 UTC, kitpao commented on README.md
> +- in terminal type: ruby index.rb
- [ ] **OPTIONAL** If you would like to format your terminal instructions as code, you can use backquotes
```
`like this`
```

2020-11-27 21:42 UTC, kitpao approved these changes
# 👋 Hi again @AbdelrhmanAmin 

You have done amazingly 🥳 All the tests are passing and 
### 👏 Your project has been approved 👏
### 🚀 You may merge to development and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-27 21:49 UTC, merged